name = "webzepetoku"
compatibility_date = "2025-02-01" # Update ke tanggal terbaru
pages_build_output_dir = "public"

compatibility_flags = ["nodejs_compat"]

[vars]
HF_API_URL = "https://webzepetoku-convert.hf.space/convert"

[[d1_databases]]
binding = "DB"
database_name = "webzepetoku"
database_id = "918a66da-6ebc-4de1-914d-c5c380291e05"